gData.x = 0:511;
gData.y = x;
gData.k = 0.5:2:510.5;
gData.l = 0:2:4;
gData.params = 2;
gData.rBF = @(x,k,params) exp(-(x-k).^2./(2*params(1)^2))./k.^2;
gData.zIP = @(r,k,params) sqrt((sqrt(2*10)*params(1)+k).^2-r^2);
G = findG(gData);
Ginv = findGinv(gData);
[U,S,V] = svd(G,0);
Up = U';
Sinv = 1./diag(S);
save(['G_r',num2str(numel(x)),'_k',num2str(numel(k)),'_l',num2str(max(l)),'_s',num2str(round(params,2)),'.mat'],'-v7.3','Up','Sinv','V','x','y','k','l','rBF','params','Ginv');